### ISSUE TITLE
좀비의 닉네임이 랜덤 혹은 직접 지정되고, 누가 이야기했는지 알 수 있는 기능이 필요합니다.

### ISSUE THREAD

**Issue by gasbank** [lacti/zombie-chat#1]
아무리 좀비라지만, 각자는 인격이 있고 이 세상에서 유일하고 소중한 존재입니다. 누가 '그워'거렸는지 구분될 수 있는 기능은 필수입니다. 이 기능이 들어간다면 이 앱을 사용하는 좀비 사이에서 더욱 더 유대감이 형성되고, 결과적으로는 앱의 실사용 신규 좀비수가 증가될 것으로 기대됩니다.

**Comment by lacti** [comment]
첫 제안 대단히 감사합니다.
대단히 유의미한 기능이오나 UI/UX에 대한 고민이 부족한 터라 일단은 다음 방향으로 수정하려 합니다.
- app을 기동하면 random으로 이름을 부여합니다.
- 이름은 chat message 위에 text로 이름을 표시합니다.
- 하는 김에 `내`가 말한 메시지는 오른쪽에 표시하고 남이 말한 메시지는 왼쪽에 표시합니다.
- 하는 김에 시간도 같이 표시합니다.

**Comment by gasbank** [comment]
만족스럽습니다.
